Add Vision and Mission statements
SparkCC/sparkcc-governance pull request #4
Opened 2022-04-29 07:44 UTC by amorphic

This PR adds SparkCC's Vision and Mission statements:

- **Vision**: What we do
- **Mission**: How we do it

2022-05-02 09:35 UTC, bulldoges requested changes
Need to update the clause reference.

2022-05-02 12:42 UTC, amorphic commented
Nice catch @bulldoges! I've updated the clause numbers within the text.

2022-05-04 11:56 UTC, bulldoges approved these changes

2022-05-04 23:07 UTC, snoopen approved these changes
Great work

2022-05-10 05:42 UTC, merged